apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: dmin
  name: dmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/prueba64-net: "true"
        io.kompose.service: dmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: info@jasoft.ec
            - name: PGADMIN_DEFAULT_PASSWORD
              value: clave
            - name: TZ
              value: America/Guayaquil
          image: dpage/pgadmin4
          name: dmin
          ports:
            - containerPort: 80
              hostPort: 5050
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
