apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: wildfly
  name: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wildfly
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/prueba64-net: "true"
        io.kompose.service: wildfly
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: mydatabase
            - name: DB_PASS
              value: mypassword
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: myuser
            - name: JAEGER_AGENT_HOST
              value: jaegertracing
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_SAMPLER_TYPE
              value: const
          image: wildfly
          name: wildfly
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - containerPort: 9990
              hostPort: 9990
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
